SELECT T.NOMBRE AS TELESERIE,AC.NOMBRE AS ACTOR , R.PROTAGONICO AS PAPEL
FROM REPARTO_ACTORES AS R
INNER JOIN TELESERIE AS T
ON R.ID_TELESERIE = T.ID
INNER JOIN ACTOR AC
ON R.ID_ACTOR = AC.ID
WHERE R.PROTAGONICO = TRUE